### ISSUE TITLE
[EPIC] Migrate to new repo

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/airbyte-python-cdk#33]
## POC "Spike" Tasks

```[tasklist]
### POC Spike Tasks
- [x] Create new repo (dry-run)
- [x] Create and run script to import pruned files and commit history from monorepo to new repo.
- [x] CI Workflow: linting check and fix
- [x] CI Workflow: formatting check and fix
- [x] CI Workflow: typing checks
- [x] Release Workflow: [started] PyPI publish + changelog?
```

```[tasklist]
### Documentation
- [ ] https://github.com/airbytehq/airbyte-python-cdk/issues/34
- [x] Documentation: make sure to leave `airbyte-cdk/README.md` with a note that we're moving to the new repo
```

## DX Workflow Demos

```[tasklist]
### DX Demo Tasks
- [x] DX Demo: How to publish the CDK
- [ ] DX Demo: Co-Develop a Connector and CDK at the Same Time
- [ ] DX Demo: How to switch a Co-Developed Connector to a published/pinned CDK ref
- [ ] DX Demo: [Something about Source Declarative Manifest]
```

## Rollout Tasks

```[tasklist]
### Rollout Tasks
- [x] Create new repo (real) [2 hrs]
- [x] Copy-in workflow updates from spike [1 hr]
- [x] Test everything, debug any issues. [3 hrs, + ~3 days blocked in an oncall style]
- [x] ~~Release Workflow: Connector Builder platform PR~~ (not needed; builder pins to CDK already)
- [ ] https://github.com/airbytehq/airbyte-python-cdk/issues/35
```

## Post-Rollout Tasks

```[tasklist]
### Post-Rollout Tasks
- [ ] https://github.com/airbytehq/airbyte-python-cdk/issues/64
- [ ] https://github.com/airbytehq/airbyte-python-cdk/issues/79
- [ ] https://github.com/airbytehq/airbyte-internal-issues/issues/10779
- [ ] https://github.com/airbytehq/airbyte-internal-issues/issues/10855
- [ ] https://github.com/airbytehq/airbyte-internal-issues/issues/10664
- [x] Update the `README.md` on the new repo and update the note about the release flow (do this once we settle SDM release flow as well)
```

## Other outstanding questions:

1. What do we need to do for Source Declarative Manifest?
1. What do we need to do for connector builder?

**Comment by aaronsteers** [comment]
Note from @maxi297 : Manifest declarative source can't parse "x.y.zrc1" format, expects three part and third part becomes zrc1.
